### ISSUE TITLE
UI Component Todo

### ISSUE THREAD

**Issue by SeBin-Kwon** [DeveloperAcademy-POSTECH/MacC-Team2-Nutty#10]
## 📌 Issue
 - UI Component를 구현합니다.

 ## 📝 To-do
 - [x] InputField #12
 - [x] CTAButton #29

**Comment by mun9769** [comment]
ios버전으로 낮추니까 `InputField`에 `@FocusState` 프로퍼티 래퍼에 ios15 이상 버전에서 사용할 수 있다고 오류가 나요
ios14버전에 맞게끔 수정해줄 수 있을까요?

**Comment by ge-um** [comment]
이거 대체 무슨 이슈야요

**Comment by SeBin-Kwon** [comment]
@ge-um 구현해야 될 디자인 시스템 컴포넌트들을 쭉 써놔서 보기 쉽게 하려는 의도,, 였는데 대부분을 노션과 피그마에서 관리하니 약간 존재감이 희미해진 이슈라고 할 수 있겟네여,,
