### ISSUE TITLE
SubmitCheckListView 수정하기

### ISSUE THREAD

**Issue by ryjmn** [DeveloperAcademy-POSTECH/MacC-Team2-Nutty#117]
## 📌 Issue
|예시1|예시2|
|---|---|
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/a22d1218-1c39-4f48-9847-a943ee117d66" width=180>|<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/12679dfd-e4ee-4f40-b5af-4e13569279c0" width=180>

 - 타이틀
     - 입력해 주세요 → 확인해 주세요
 - CTA 문구
     - 다음 → 수정 완료
 - InputField(Stack UI)
     - 해당 정보만 노출 _(ex: 어르신 성함 수정 시, 전화번호와 주민번호 입력필드는 노출 X)_

***
자세한 사항은 피그마 Hi-Fi 페이지에
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/5d6f9f1d-4450-4551-a7e7-b3fb0ac929c5">

**Comment by mun9769** [comment]
준유가 확인하고, close 해줘요
