### ISSUE TITLE
📷 수동촬영

### ISSUE THREAD

**Issue by JJunghyunY** [DeveloperAcademy-POSTECH/MacC-Team2-Nutty#118]
## 📌 Issue
 - 자동촬영과 수동촬영의 사용자 테스트 비교를 위함

 ## 📝 To-do
 - [ ] 수동촬영

**Comment by mun9769** [comment]
자동촬영으로 바꾸니까 애뮬레이터에서 넘어갈 수가 없어요 빨리 만들어주세요~~

**Comment by JJunghyunY** [comment]
Done
