### ISSUE TITLE
Modify SubmitCheckListView ( ~ 11/9 )

### ISSUE THREAD

**Issue by mun9769** [DeveloperAcademy-POSTECH/MacC-Team2-Nutty#127]
## 📌 Issue
#115 이슈가 커서 작은 이슈로 쪼갠다. 
This closes #115 

 ## 📝 To-do
**SubmitCheckListView**
<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team2-Nutty/assets/85615266/d5045922-f2ee-4a61-9ec1-dcf8852ece8a" width=180>
- 텍스트
- [x] 대리인 → 실제 사용자 이름 (ex: 김유진)
- [x] 패딩: 좌우 패딩이 조금 좁음 → CTA 버튼과 맞출 것
- 체크박스_오류🚨
- [x] 체크박스 해제가 안 되는 오류 O

**Comment by SeBin-Kwon** [comment]
저와 미야가 해결한 이슈입니다~~~
#141 
#135
