### ISSUE TITLE
Update ApplyHistoryView

### ISSUE THREAD

**Issue by SeBin-Kwon** [DeveloperAcademy-POSTECH/MacC-Team2-Nutty#166]
## 📌 Issue
 - 변경된 ApplyHistoryView로 업데이트합니다.

 ## 📝 To-do
 - [x] ApplyHistoryView

**Comment by mun9769** [comment]
https://www.youtube.com/watch?v=RkfJoNzfJ8w&t=361s
사진 줌인아웃할 수 있는 튜토리얼이 있네요 참고하면 좋을듯요
