### ISSUE TITLE
Create mainView / Create views with stacking animation / Create simple selecting view

### ISSUE THREAD

**Issue by mun9769** [DeveloperAcademy-POSTECH/MacC-Team2-Nutty#24]
## 📌 Issue
 - 피그마의 뷰를 그린다. 
 - 애니메이션을 구현한다. 

 ## 📝 To-do
 - [x] MainView
 - [x] ApplyTypeView
 - [x] MediHistoryView
 - [x] PatientInfoView(애니메이션)
 - [x] RejectView
 - [x] MediConditionView

## 네비게이션 전략
// TODO

**Comment by JJunghyunY** [comment]
issue 어체가 문도같아요

**Comment by mun9769** [comment]
문도 개발한다

**Comment by ge-um** [comment]
아니 이슈 이름이 이게모람 ㅋㅋㅋㅋ

**Comment by ge-um** [comment]
저 뭐야 사실 이것은 제가 태스크 빨리 안 나눠서 일어난 거긴 하지만 이슈 이름 개조식 동사+명사 이런 식으로 지어주세요! ex)Create View @JJunghyunY @mun9769 @SeBin-Kwon

**Comment by ge-um** [comment]
에렌 그리고 지금은 파버려서 어쩔 수 없지만 ... . 뷰 나눠서 이슈 파요 ㅠㅠ~ 전부 다 파는 건 귀찮으니까 ex) Create MainView / Create views with stacking animation / Create simple selecting view 이런 식으로요~ 지금이야 분배한 게 기억나지만 나중에 찾으려면 찾기 어려울 것 같아요 ㅠ @mun9769
