### ISSUE TITLE
Design Modification

### ISSUE THREAD

**Issue by JJunghyunY** [DeveloperAcademy-POSTECH/MacC-Team2-Nutty#62]
## 📌 Issue

 <!— 이슈에 대해 간략하게 설명해주세요 —> 
 - AddressFormView 로직 수정
 - ~컴포넌트 디자인 적용~

 ## 📝 To-do
 <!- 진행할 작업에 대해 적어주세요 ->
 - [x] AddressFormView 로직 수정
 - [x] IDCardConfirmEditView 수정 및 HomeNavigation 연결
 - [x] SubmitCheckListView: Capsule -> RoundedRectangle

**Comment by ge-um** [comment]
... 먼데요~~~~~~~
